### PR TITLE
Add discount rules

### LINKED ISSUE #12: Add discounts to be applied for specific purchase combinations
We must add a mechanism for discounts to be applied to purchases which meet specific criteria. 

For security reasons, this should be handled by the backend to ensure that people aren't able to duplicate valid discounts in sessionStorage and set the price to $0.00 charged. 

Therefore, I propose we create something like `func calculateDiscounts (Items[] items) int64` which will look through the cart and apply discounts to the total cost if purchases meet certain criteria. Stripe offers functionality for coupons (discounts) however, these don't work with the traditional payment intents (only God knows why...).

The criteria which warrant discounts are:

buy a hoodie + 1 item - $5 off
buy a hoodie + 2 items - $10 off

### PR DESCRIPTION
**Pull request by lhvy**
Resolves #12

### CODE REVIEW

**Comment by scorpiontornado** [comment]
Could be worth making sure the total is never < 0. Probably impossible, but could be a good idea in case of a mistake when adding new discounts in future.

**Comment by scorpiontornado** [comment]
Also, might be worth having a `func calculateDiscounts (Items[] items) int64` function like @theawesomew suggested. Or, just a function with num items and a bool of whether there's a hoodie there or not.

**Comment by theawesomew** [comment]
Please capitalize the constant 'hoodie_id' to distinguish it from other local variables.



> Could be worth making sure the total is never < 0. Probably impossible, but could be a good idea in case of a mistake when adding new discounts in future.

Stripe will consider any negative charge a rebate to the consumer. So, if this happens it won't break anything but, it would be... interesting. I do agree that it's probably worthwhile to prevent regardless.

**Comment by theawesomew** [comment]
> Also, might be worth having a `func calculateDiscounts (Items[] items) int64` function like @theawesomew suggested. Or, just a function with num items and a bool of whether there's a hoodie there or not.

I'm torn about doing this. I feel that it's generally useful to only have one return statement per function and any mutations to the return that can occur should occur pre-returning the value (generally speaking, of course). BUT, I don't know if creating an entirely separate function is worthwhile given the simplicity of the discount feature and it only being used in one place. So, 50/50 about whether or not it adds to simplicity of the codebase or just creates more pointless jumping around for a potential future-maintainer of the code.

**Comment by lhvy** [comment]
> Could be worth making sure the total is never < 0. Probably impossible, but could be a good idea in case of a mistake when adding new discounts in future.

Fixed

**Comment by lhvy** [comment]
> > Also, might be worth having a `func calculateDiscounts (Items[] items) int64` function like @theawesomew suggested. Or, just a function with num items and a bool of whether there's a hoodie there or not.
> 
> I'm torn about doing this. I feel that it's generally useful to only have one return statement per function and any mutations to the return that can occur should occur pre-returning the value (generally speaking, of course). BUT, I don't know if creating an entirely separate function is worthwhile given the simplicity of the discount feature and it only being used in one place. So, 50/50 about whether or not it adds to simplicity of the codebase or just creates more pointless jumping around for a potential future-maintainer of the code.

I didn't want to do this as it would lead to code duplication and seemed to be a very simple task to do in the same spot as calculating the price. Provided the extra logic is well commented, I don't see the problem with a few extra lines.

**Comment by scorpiontornado** [comment]
> I didn't want to do this as it would lead to code duplication and seemed to be a very simple task to do in the same spot as calculating the price. Provided the extra logic is well commented, I don't see the problem with a few extra lines.

I don't have much of an opinion, I was just considering that it might be a pain to change the discounts in future if it isn't modularised. Future maintainers would have to change multiple, separated lines rather than deleting and rewriting a calculateDiscount() function. If you clearly comment what lines are (removable) discount code vs necessary order calculations, it's not too much of an issue.

**Pull request merged**
